addons:
  apt:
    packages:
    - graphviz

language: python

python:
  - "3.8"
  - "3.9"

# command to install dependencies
install:
  - git clone https://github.com/NeuroML/NeuroMLlite.git
  - cd NeuroMLlite
  - git checkout master  # specific branch of NeuroMLlite to use...
  - python setup.py install
  - cd ..
  - pip install .


script:
  ###       Run main tests
  - pip install pytest-benchmark
  - ./test_all.sh
  - pip freeze  # List currently installed Python packages
